# Generated by Django 3.2.13 on 2023-09-27 04:45

from django.db import migrations, models
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=store.models.profile_path),
            preserve_default=False,
        ),
    ]
